-- MySQL Script generated by MySQL Workbench
-- Sat May 15 17:31:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UtfDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema UtfDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UtfDB` DEFAULT CHARACTER SET utf8 ;
USE `UtfDB` ;

-- -----------------------------------------------------
-- Table `UtfDB`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtfDB`.`Student` (
  `idStudent` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `register` VARCHAR(15) NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtfDB`.`Doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtfDB`.`Doctor` (
  `idDoctor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `specialty` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `register` VARCHAR(15) NULL,
  PRIMARY KEY (`idDoctor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtfDB`.`Appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtfDB`.`Appointment` (
  `idAppointment` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `time` TIME NULL,
  `place` VARCHAR(100) NULL,
  `observations` VARCHAR(500) NULL,
  `Doctor_idDoctor` INT NOT NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idAppointment`, `Student_idStudent`),
  INDEX `fk_Appointment_Doctor1_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  INDEX `fk_Appointment_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_Appointment_Doctor1`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `UtfDB`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Appointment_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `UtfDB`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtfDB`.`medicalHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtfDB`.`medicalHistory` (
  `idmedicalHistory` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NULL,
  `Student_idStudent` INT NOT NULL,
  PRIMARY KEY (`idmedicalHistory`, `Student_idStudent`),
  INDEX `fk_medicalHistory_Student1_idx` (`Student_idStudent` ASC) VISIBLE,
  CONSTRAINT `fk_medicalHistory_Student1`
    FOREIGN KEY (`Student_idStudent`)
    REFERENCES `UtfDB`.`Student` (`idStudent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UtfDB`.`Schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UtfDB`.`Schedules` (
  `idSchedules` INT NOT NULL AUTO_INCREMENT,
  `data` JSON NULL,
  `Doctor_idDoctor` INT NOT NULL,
  PRIMARY KEY (`idSchedules`),
  INDEX `fk_Schedules_Doctor_idx` (`Doctor_idDoctor` ASC) VISIBLE,
  CONSTRAINT `fk_Schedules_Doctor`
    FOREIGN KEY (`Doctor_idDoctor`)
    REFERENCES `UtfDB`.`Doctor` (`idDoctor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
