@base_address = http://localhost:3000

get {{base_address}}/appointment

###
get {{base_address}}/appointment/33

###
patch {{base_address}}/appointment
content-Type: application/json

{
   "date": "",
   "time": "",
   "place": "",
   "observations": "",
   "Doctor_idDoctor": "",
   "Student_idStudent": "",
   "idAppointment" : "",

}


###
post {{base_address}}/appointment
content-Type: application/json

{
   
  "Student_idStudent": "",
  "Doctor_idDoctor": "",
  "date":"",
  "time": "",
  "place": "",
  "observations": "",
  
}

###
delete {{base_address}}/appointment
content-Type: application/json

{
   "idAppointment":"",

}