@base_address = http://localhost:3000


###
get {{base_address}}/doctor

###
get {{base_address}}/doctor/2


###
post {{base_address}}/doctor
content-Type: application/json

{
   "name": "Adriana",
   "specialty": "Dentista",
   "email": "adriana@exemplo",
   "register": "s44444", 
   "password" : "123"

}

###
patch {{base_address}}/doctor
content-Type: application/json

{
   "name": "alter",
   "specialty": "alter",
   "email": "email",
   "register": "register",
   "password" : "123",
   "idDoctor": 1

}

###
delete {{base_address}}/doctor
content-Type: application/json

{

   "idDoctor": 2

}
