@base_address = http://localhost:3000

###
get {{base_address}}/medicalHistory

###
get {{base_address}}/medicalHistory/7


/////////////////////////NAO TA FUNCIONANDO
###
post {{base_address}}/medicalHistory
content-Type: application/json

{
   "Student_idStudent": "1",
   "data":   { "data": {
      
            "allergy":"req.body.allergy",
            "chronicDisease":" chronicDisease",
            "familyDisease":"familyDisease",
            "caries":"caries",
            "dentalAppliance":"dentalAppliance",
            "canal":"canal",
            "wisdomExtraction":"wisdomExtraction",
            "psychologicalSupport":"psychologicalSupport",
            "tdah":"tdah",
            "anxiety":"anxiety",
            "antidepressant":"antidepressant",
            "schedules":"schedules",
            "routine":"routine",
            "pedagogicalSupport":"pedagogicalSupport"
      
   }
   }
}

###
patch {{base_address}}/medicalHistory
content-Type: application/json

{
   "Student_idStudent": "1",
   "data":   { "data": {
      
            "allergy":"req.body.allergy",
            "chronicDisease":" chronicDisease",
            "familyDisease":"familyDisease",
            "caries":"caries",
            "dentalAppliance":"dentalAppliance",
            "canal":"canal",
            "wisdomExtraction":"wisdomExtraction",
            "psychologicalSupport":"psychologicalSupport",
            "tdah":"tdah",
            "anxiety":"anxiety",
            "antidepressant":"antidepressant",
            "schedules":"schedules",
            "routine":"routine",
            "pedagogicalSupport":"pedagogicalSupport"
      
   }
   },
   "idmedicalHistory": 7
}

###
delete {{base_address}}/medicalHistory
content-Type: application/json

{

   "idmedicalHistory": 7

}

