@base_address = http://localhost:3000


###
get {{base_address}}/schedules

###
get {{base_address}}/schedules/4


###
post {{base_address}}/schedules
content-Type: application/json

{
  "data": {"tomanocu": 1},
   "Doctor_idDoctor":"7"
}

###
patch {{base_address}}/schedules
content-Type: application/json

{
    "data":   { "data": { } },
   "Doctor_idDoctor":"7",
   "idSchedules": "4"

}

###
delete {{base_address}}/schedules
content-Type: application/json

{
   "idSchedules": 2
}
