@base_address = http://localhost:3000

###
get {{base_address}}/student

###
get {{base_address}}/student/12

###
post {{base_address}}/student
content-Type: application/json

{
   "email": "",
   "name": "",
   "register": "",
   "password": ""
   
}

###
patch {{base_address}}/student
content-Type: application/json

{
   "name": "",
   "email": "",
   "register": "",
   "password": "",
   "idStudent": "",
  
}

###
delete {{base_address}}/student
content-Type: application/json

{
   "idStudent": "",
}

###'
post {{base_address}}/student/auth
content-Type: application/json

{
   "register": "",
   "password": """,
   
}
