@base_address = http://localhost:3000


###
get {{base_address}}/student

###
get {{base_address}}/student/12

###
post {{base_address}}/student
content-Type: application/json

{
   "email": "email",
   "name": "name",
   "register": "101010",
   "password": "123456"
   
}

###
patch {{base_address}}/student
content-Type: application/json

{
   "name": "Vinicius",
   "email": "email",
   "register": "register",
   "password": "1233",
   "idStudent": 12
  
}

###
delete {{base_address}}/student
content-Type: application/json

{
   "idStudent": 2
}
